//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.11 at 04:33:43 PM EEST 
//


package com.ing.ideal.connector.binding;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.idealdesk.ideal.messages.mer_acq._3_3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.idealdesk.ideal.messages.mer_acq._3_3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcquirerErrorRes }
     * 
     */
    public AcquirerErrorRes createAcquirerErrorRes() {
        return new AcquirerErrorRes();
    }

    /**
     * Create an instance of {@link AcquirerStatusReq }
     * 
     */
    public AcquirerStatusReq createAcquirerStatusReq() {
        return new AcquirerStatusReq();
    }

    /**
     * Create an instance of {@link AcquirerStatusRes }
     * 
     */
    public AcquirerStatusRes createAcquirerStatusRes() {
        return new AcquirerStatusRes();
    }

    /**
     * Create an instance of {@link DirectoryRes }
     * 
     */
    public DirectoryRes createDirectoryRes() {
        return new DirectoryRes();
    }

    /**
     * Create an instance of {@link DirectoryReq }
     * 
     */
    public DirectoryReq createDirectoryReq() {
        return new DirectoryReq();
    }

    /**
     * Create an instance of {@link AcquirerTrxRes }
     * 
     */
    public AcquirerTrxRes createAcquirerTrxRes() {
        return new AcquirerTrxRes();
    }

    /**
     * Create an instance of {@link AcquirerTrxReq }
     * 
     */
    public AcquirerTrxReq createAcquirerTrxReq() {
        return new AcquirerTrxReq();
    }

    /**
     * Create an instance of {@link DirectoryRes.Directory }
     * 
     */
    public DirectoryRes.Directory createDirectoryResDirectory() {
        return new DirectoryRes.Directory();
    }

    /**
     * Create an instance of {@link DirectoryRes.Directory.Country }
     * 
     */
    public DirectoryRes.Directory.Country createDirectoryResDirectoryCountry() {
        return new DirectoryRes.Directory.Country();
    }

    /**
     * Create an instance of {@link AcquirerErrorRes.Error }
     * 
     */
    public AcquirerErrorRes.Error createAcquirerErrorResError() {
        return new AcquirerErrorRes.Error();
    }

    /**
     * Create an instance of {@link AcquirerStatusReq.Merchant }
     * 
     */
    public AcquirerStatusReq.Merchant createAcquirerStatusReqMerchant() {
        return new AcquirerStatusReq.Merchant();
    }

    /**
     * Create an instance of {@link AcquirerStatusReq.Transaction }
     * 
     */
    public AcquirerStatusReq.Transaction createAcquirerStatusReqTransaction() {
        return new AcquirerStatusReq.Transaction();
    }

    /**
     * Create an instance of {@link AcquirerStatusRes.Acquirer }
     * 
     */
    public AcquirerStatusRes.Acquirer createAcquirerStatusResAcquirer() {
        return new AcquirerStatusRes.Acquirer();
    }

    /**
     * Create an instance of {@link AcquirerStatusRes.Transaction }
     * 
     */
    public AcquirerStatusRes.Transaction createAcquirerStatusResTransaction() {
        return new AcquirerStatusRes.Transaction();
    }

    /**
     * Create an instance of {@link DirectoryRes.Acquirer }
     * 
     */
    public DirectoryRes.Acquirer createDirectoryResAcquirer() {
        return new DirectoryRes.Acquirer();
    }

    /**
     * Create an instance of {@link DirectoryReq.Merchant }
     * 
     */
    public DirectoryReq.Merchant createDirectoryReqMerchant() {
        return new DirectoryReq.Merchant();
    }

    /**
     * Create an instance of {@link AcquirerTrxRes.Acquirer }
     * 
     */
    public AcquirerTrxRes.Acquirer createAcquirerTrxResAcquirer() {
        return new AcquirerTrxRes.Acquirer();
    }

    /**
     * Create an instance of {@link AcquirerTrxRes.Issuer }
     * 
     */
    public AcquirerTrxRes.Issuer createAcquirerTrxResIssuer() {
        return new AcquirerTrxRes.Issuer();
    }

    /**
     * Create an instance of {@link AcquirerTrxRes.Transaction }
     * 
     */
    public AcquirerTrxRes.Transaction createAcquirerTrxResTransaction() {
        return new AcquirerTrxRes.Transaction();
    }

    /**
     * Create an instance of {@link AcquirerTrxReq.Issuer }
     * 
     */
    public AcquirerTrxReq.Issuer createAcquirerTrxReqIssuer() {
        return new AcquirerTrxReq.Issuer();
    }

    /**
     * Create an instance of {@link AcquirerTrxReq.Merchant }
     * 
     */
    public AcquirerTrxReq.Merchant createAcquirerTrxReqMerchant() {
        return new AcquirerTrxReq.Merchant();
    }

    /**
     * Create an instance of {@link AcquirerTrxReq.Transaction }
     * 
     */
    public AcquirerTrxReq.Transaction createAcquirerTrxReqTransaction() {
        return new AcquirerTrxReq.Transaction();
    }

    /**
     * Create an instance of {@link DirectoryRes.Directory.Country.Issuer }
     * 
     */
    public DirectoryRes.Directory.Country.Issuer createDirectoryResDirectoryCountryIssuer() {
        return new DirectoryRes.Directory.Country.Issuer();
    }

}
