//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.11 at 04:33:43 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.idealdesk.com/ideal/messages/mer-acq/3.3.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ing.ideal.connector.binding;
